# CDF

In [ ]:
def draw_cdf(np_result):
    fig = plt.figure(figsize=(15,10))
    fig.set_facecolor('white')
    ax = fig.add_subplot()
    
    sorted_data = np.sort(np_result)
    plt.step(sorted_data, np.arange(sorted_data.size), cumulative=True, density=True)

    # plt.xscale('symlog')

    plt.show()

In [ ]:
def draw_multiple_cdf(np_result_list, title, colors, legends, xlabel):
    filename = title + '.png'
    fig = plt.figure(figsize=(15,10))
    fig.set_facecolor('white')
    ax = fig.add_subplot()
    
    for np_result, color, legend in zip(np_result_list, colors, legends):
        sorted_data = np.sort(np_result)
        plt.step(sorted_data, np.arange(sorted_data.size), label=legend, color=color)
        plt.xlabel(xlabel, fontsize=12)
        plt.title(title, fontsize=18)
  
    plt.legend(fontsize=14)
    plt.savefig(filename, dpi=300)
    plt.show()

In [ ]:
def draw_multiple_cdf_log(np_result_list, title, colors, legends, xlabel):
    filename = title + '.png'
    fig = plt.figure(figsize=(15,10))
    fig.set_facecolor('white')
    ax = fig.add_subplot()
    
    for np_result, color, legend in zip(np_result_list, colors, legends):
        sorted_data = np.sort(np_result)
        plt.step(sorted_data, np.arange(sorted_data.size), label=legend, color=color)
        plt.xlabel(xlabel, fontsize=12)
        plt.title(title, fontsize=18)
        plt.xscale('symlog')
  
    plt.legend(fontsize=14)
    plt.savefig(filename, dpi=300)
    plt.show()

In [ ]:
def draw_cdf_density(np_result_list, title, xlabel, legends, log_scale):
    filename = title + '.png'
    sns.set(rc={'figure.figsize':(11.7,8.27)})
    kwargs = {'cumulative': True}
    
    fig = plt.figure(figsize=(15,10))
    fig.set_facecolor('white')
    
    for np_result in np_result_list:
        ax = sns.distplot(np_result, hist_kws=kwargs, kde_kws=kwargs, hist=False, norm_hist=False)
        ax.set_title(title)
        ax.set_xlabel(xlabel)
        plt.title(title, fontsize=18)
        plt.xlabel(xlabel, fontsize=12)
        plt.legend(labels=legends, fontsize=14)
        if log_scale:
            plt.xscale('symlog')
    
    plt.savefig(filename, dpi=300)

# Boxplot

In [ ]:
def draw_boxplot(result_list, title):
    filename = title + '.png'
    
    plt.rcParams['figure.figsize'] = [20, 15]
    xlabel = ['IS score 1', 'IS score 2', 'IS score 3', 'ES score 1', 'ES score 2', 'ES score 3']

    plt.boxplot(result_list, showfliers=True)
    plt.xticks([1, 2, 3, 4, 5, 6], xlabel, fontsize=20)
    plt.yticks(fontsize=20)
    # plt.ylabel('Vote', fontsize=24)
    plt.yscale('log')
    # plt.title(title, fontsize=30)
    
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    
    plt.show()

In [ ]:
connection = cn.make_connection('connection.csv')

cursors3 = []
sqls3 = []
results3 = []
result_list3 = []
for i in range(6):
    cursors3.append(connection.cursor(pymysql.cursors.DictCursor))

where = "is_valid=1 and is_valid_author=1;"

sqls3.append("select score from comments where is_score = 1 and " + where)
sqls3.append("select score from comments where is_score = 2 and " + where)
sqls3.append("select score from comments where is_score = 3 and " + where)
sqls3.append("select score from comments where es_score = 1 and " + where)
sqls3.append("select score from comments where es_score = 2 and " + where)
sqls3.append("select score from comments where es_score = 3 and " + where)

for i in range(6):
    cursors3[i].execute(sqls3[i])
    # result가 dict 형태로 return.
    results3.append(cursors3[i].fetchall())

connection.close()

for i in range(6):
    results3[i] = pd.DataFrame(results3[i])
    result_list3.append(list(np.array(results3[i]['score'].tolist())))

In [ ]:
draw_boxplot(result_list3, "boxplot_support_score_vote")

In [ ]:
connection = cn.make_connection('connection.csv')

cursors3 = []
sqls3 = []
results3 = []
result_list3 = []
for i in range(6):
    cursors3.append(connection.cursor(pymysql.cursors.DictCursor))

sqls3.append("select score from comments where is_score = 1 and is_valid_author=1 and is_valid=1;")
sqls3.append("select score from comments where is_score = 2 and is_valid_author=1 and is_valid=1;")
sqls3.append("select score from comments where is_score = 3 and is_valid_author=1 and is_valid=1;")
sqls3.append("select score from comments where es_score = 1 and is_valid_author=1 and is_valid=1;")
sqls3.append("select score from comments where es_score = 2 and is_valid_author=1 and is_valid=1;")
sqls3.append("select score from comments where es_score = 3 and is_valid_author=1 and is_valid=1;")

for i in range(6):
    cursors3[i].execute(sqls3[i])
    # result가 dict 형태로 return.
    results3.append(cursors3[i].fetchall())

connection.close()

for i in range(6):
    results3[i] = pd.DataFrame(results3[i])
    result_list3.append(list(np.array(results3[i]['score'].tolist())))

In [ ]:
draw_boxplot(result_list3, "boxplot_support_score_vote")

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(6):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select outdegree from nodes where top_k_outdegree = 0.1;')
sqls.append('select outdegree from nodes where top_k_outdegree > 0.1;')
sqls.append('select outdegree from nodes where top_k_outdegree <= 1;')
sqls.append('select outdegree from nodes where top_k_outdegree > 1;')
sqls.append('select outdegree from nodes where top_k_outdegree <= 10;')
sqls.append('select outdegree from nodes where top_k_outdegree > 10;')

for i in range(6):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(6):
    results[i] = pd.DataFrame(results[i])
    result_list.append(list(np.array(results[i]['outdegree'].tolist())))

In [ ]:
xlabel = ['0.1% hub', '99.9% non-hub', '1% hub', '99% non-hub', '10% hub', '90% non-hub']
draw_boxplot_for_hub(result_list, "Outdegree hub & non-hub's outdegree", xlabel, 'outdegree')

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(6):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select indegree from nodes where top_k_outdegree = 0.1;')
sqls.append('select indegree from nodes where top_k_outdegree > 0.1;')
sqls.append('select indegree from nodes where top_k_outdegree <= 1;')
sqls.append('select indegree from nodes where top_k_outdegree > 1;')
sqls.append('select indegree from nodes where top_k_outdegree <= 10;')
sqls.append('select indegree from nodes where top_k_outdegree > 10;')

for i in range(6):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(6):
    results[i] = pd.DataFrame(results[i])
    result_list.append(list(np.array(results[i]['indegree'].tolist())))

In [ ]:
draw_boxplot_for_hub(result_list, "Outdegree hub & non-hub's indegree", xlabel, 'indegree')

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(6):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select m.posts_similarity from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree = 0.1 and m.posts_similarity is not null;')
sqls.append('select m.posts_similarity from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 0.1 and m.posts_similarity is not null;')
sqls.append('select m.posts_similarity from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree <= 1 and m.posts_similarity is not null;')
sqls.append('select m.posts_similarity from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 1 and m.posts_similarity is not null;')
sqls.append('select m.posts_similarity from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree <= 10 and m.posts_similarity is not null;')
sqls.append('select m.posts_similarity from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 10 and m.posts_similarity is not null;')

for i in range(6):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(6):
    results[i] = pd.DataFrame(results[i])
    # decimal을 float형으로 형 변환.
    results[i] = results[i].apply(pd.to_numeric, downcast='float')
    result_list.append(list(np.array(results[i]['posts_similarity'].tolist())))

In [ ]:
draw_boxplot_for_hub(result_list, "Outdegree hub & non-hub's posts similarity", xlabel, 'posts similarity')

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(6):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select m.comments_similarity from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree = 0.1 and m.comments_similarity is not null;')
sqls.append('select m.comments_similarity from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 0.1 and m.comments_similarity is not null;')
sqls.append('select m.comments_similarity from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree <= 1 and m.comments_similarity is not null;')
sqls.append('select m.comments_similarity from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 1 and m.comments_similarity is not null;')
sqls.append('select m.comments_similarity from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree <= 10 and m.comments_similarity is not null;')
sqls.append('select m.comments_similarity from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 10 and m.comments_similarity is not null;')

for i in range(6):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(6):
    results[i] = pd.DataFrame(results[i])
    # decimal을 float형으로 형 변환.
    results[i] = results[i].apply(pd.to_numeric, downcast='float')
    result_list.append(list(np.array(results[i]['comments_similarity'].tolist())))

In [ ]:
draw_boxplot_for_hub(result_list, "Outdegree hub & non-hub's comments similarity", xlabel, 'comments similarity')

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(6):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select m.average_is_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree = 0.1;')
sqls.append('select m.average_is_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 0.1;')
sqls.append('select m.average_is_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree <= 1;')
sqls.append('select m.average_is_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 1;')
sqls.append('select m.average_is_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree <= 10;')
sqls.append('select m.average_is_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 10;')

for i in range(6):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(6):
    results[i] = pd.DataFrame(results[i])
    # decimal을 float형으로 형 변환.
    results[i] = results[i].apply(pd.to_numeric, downcast='float')
    result_list.append(list(np.array(results[i]['average_is_score'].tolist())))

In [ ]:
draw_boxplot_for_hub(result_list, "Outdegree hub & non-hub's average is score", xlabel, 'average is score')

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(6):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select m.average_es_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree = 0.1;')
sqls.append('select m.average_es_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 0.1;')
sqls.append('select m.average_es_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree <= 1;')
sqls.append('select m.average_es_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 1;')
sqls.append('select m.average_es_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree <= 10;')
sqls.append('select m.average_es_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 10;')

for i in range(6):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(6):
    results[i] = pd.DataFrame(results[i])
    # decimal을 float형으로 형 변환.
    results[i] = results[i].apply(pd.to_numeric, downcast='float')
    result_list.append(list(np.array(results[i]['average_es_score'].tolist())))

In [ ]:
draw_boxplot_for_hub(result_list, "Outdegree hub & non-hub's average es score", xlabel, 'average es score')

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(6):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select m.average_vote from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree = 0.1;')
sqls.append('select m.average_vote from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 0.1;')
sqls.append('select m.average_vote from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree <= 1;')
sqls.append('select m.average_vote from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 1;')
sqls.append('select m.average_vote from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree <= 10;')
sqls.append('select m.average_vote from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 10;')

for i in range(6):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(6):
    results[i] = pd.DataFrame(results[i])
    # decimal을 float형으로 형 변환.
    results[i] = results[i].apply(pd.to_numeric, downcast='float')
    result_list.append(list(np.array(results[i]['average_vote'].tolist())))

In [ ]:
draw_boxplot_for_hub(result_list, "Outdegree hub & non-hub's average vote", xlabel, 'average vote')

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(6):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select outdegree from nodes where top_k_indegree = 0.1;')
sqls.append('select outdegree from nodes where top_k_indegree > 0.1;')
sqls.append('select outdegree from nodes where top_k_indegree <= 1;')
sqls.append('select outdegree from nodes where top_k_indegree > 1;')
sqls.append('select outdegree from nodes where top_k_indegree <= 10;')
sqls.append('select outdegree from nodes where top_k_indegree > 10;')

for i in range(6):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(6):
    results[i] = pd.DataFrame(results[i])
    result_list.append(list(np.array(results[i]['outdegree'].tolist())))

In [ ]:
draw_boxplot_for_hub(result_list, "Indegree hub & non-hub's outdegree", xlabel, 'outdegree')

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(6):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select indegree from nodes where top_k_indegree = 0.1;')
sqls.append('select indegree from nodes where top_k_indegree > 0.1;')
sqls.append('select indegree from nodes where top_k_indegree <= 1;')
sqls.append('select indegree from nodes where top_k_indegree > 1;')
sqls.append('select indegree from nodes where top_k_indegree <= 10;')
sqls.append('select indegree from nodes where top_k_indegree > 10;')

for i in range(6):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(6):
    results[i] = pd.DataFrame(results[i])
    result_list.append(list(np.array(results[i]['indegree'].tolist())))

In [ ]:
draw_boxplot_for_hub(result_list, "Indegree hub & non-hub's indegree", xlabel, 'indegree')

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(6):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select m.average_is_score from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree = 0.1 and m.average_is_score is not null;')
sqls.append('select m.average_is_score from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 0.1 and m.average_is_score is not null;')
sqls.append('select m.average_is_score from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree <= 1 and m.average_is_score is not null;')
sqls.append('select m.average_is_score from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 1 and m.average_is_score is not null;')
sqls.append('select m.average_is_score from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree <= 10 and m.average_is_score is not null;')
sqls.append('select m.average_is_score from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 10 and m.average_is_score is not null;')

for i in range(6):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(6):
    results[i] = pd.DataFrame(results[i])
    # decimal을 float형으로 형 변환.
    results[i] = results[i].apply(pd.to_numeric, downcast='float')
    result_list.append(list(np.array(results[i]['average_is_score'].tolist())))

In [ ]:
draw_boxplot_for_hub(result_list, "Indegree hub & non-hub's average is score", xlabel, 'average is score')

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(6):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select m.average_es_score from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree = 0.1 and m.average_es_score is not null;')
sqls.append('select m.average_es_score from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 0.1 and m.average_es_score is not null;')
sqls.append('select m.average_es_score from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree <= 1 and m.average_es_score is not null;')
sqls.append('select m.average_es_score from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 1 and m.average_es_score is not null;')
sqls.append('select m.average_es_score from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree <= 10 and m.average_es_score is not null;')
sqls.append('select m.average_es_score from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 10 and m.average_es_score is not null;')

for i in range(6):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(6):
    results[i] = pd.DataFrame(results[i])
    # decimal을 float형으로 형 변환.
    results[i] = results[i].apply(pd.to_numeric, downcast='float')
    result_list.append(list(np.array(results[i]['average_es_score'].tolist())))

In [ ]:
draw_boxplot_for_hub(result_list, "Indegree hub & non-hub's average es score", xlabel, 'average es score')

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(6):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select m.average_comments_vote from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree = 0.1 and m.average_comments_vote is not null;')
sqls.append('select m.average_comments_vote from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 0.1 and m.average_comments_vote is not null;')
sqls.append('select m.average_comments_vote from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree <= 1 and m.average_comments_vote is not null;')
sqls.append('select m.average_comments_vote from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 1 and m.average_comments_vote is not null;')
sqls.append('select m.average_comments_vote from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree <= 10 and m.average_comments_vote is not null;')
sqls.append('select m.average_comments_vote from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 10 and m.average_comments_vote is not null;')

for i in range(6):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(6):
    results[i] = pd.DataFrame(results[i])
    # decimal을 float형으로 형 변환.
    results[i] = results[i].apply(pd.to_numeric, downcast='float')
    result_list.append(list(np.array(results[i]['average_comments_vote'].tolist())))

In [ ]:
draw_boxplot_for_hub(result_list, "Indegree hub & non-hub's average vote(comments)", xlabel, 'average comments vote')

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(6):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select m.average_vote from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree = 0.1 and m.average_vote is not null;')
sqls.append('select m.average_vote from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 0.1 and m.average_vote is not null;')
sqls.append('select m.average_vote from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree <= 1 and m.average_vote is not null;')
sqls.append('select m.average_vote from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 1 and m.average_vote is not null;')
sqls.append('select m.average_vote from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree <= 10 and m.average_vote is not null;')
sqls.append('select m.average_vote from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 10 and m.average_vote is not null;')

for i in range(6):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(6):
    results[i] = pd.DataFrame(results[i])
    # decimal을 float형으로 형 변환.
    results[i] = results[i].apply(pd.to_numeric, downcast='float')
    result_list.append(list(np.array(results[i]['average_vote'].tolist())))

In [ ]:
draw_boxplot_for_hub(result_list, "Indegree hub & non-hub's average vote(posts)", xlabel, 'average posts vote')

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(6):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select m.posts_similarity from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree = 0.1 and m.posts_similarity is not null;')
sqls.append('select m.posts_similarity from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 0.1 and m.posts_similarity is not null;')
sqls.append('select m.posts_similarity from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree <= 1 and m.posts_similarity is not null;')
sqls.append('select m.posts_similarity from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 1 and m.posts_similarity is not null;')
sqls.append('select m.posts_similarity from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree <= 10 and m.posts_similarity is not null;')
sqls.append('select m.posts_similarity from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 10 and m.posts_similarity is not null;')

for i in range(6):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(6):
    results[i] = pd.DataFrame(results[i])
    # decimal을 float형으로 형 변환.
    results[i] = results[i].apply(pd.to_numeric, downcast='float')
    result_list.append(list(np.array(results[i]['posts_similarity'].tolist())))

In [ ]:
draw_boxplot_for_hub(result_list, "Indegree hub & non-hub's posts similarity", xlabel, 'posts similarity')

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(6):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select m.comments_similarity from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree = 0.1 and m.comments_similarity is not null;')
sqls.append('select m.comments_similarity from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 0.1 and m.comments_similarity is not null;')
sqls.append('select m.comments_similarity from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree <= 1 and m.comments_similarity is not null;')
sqls.append('select m.comments_similarity from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 1 and m.comments_similarity is not null;')
sqls.append('select m.comments_similarity from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree <= 10 and m.comments_similarity is not null;')
sqls.append('select m.comments_similarity from nodes n, mentee m where n.node_id = m.author and n.top_k_indegree > 10 and m.comments_similarity is not null;')

for i in range(6):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(6):
    results[i] = pd.DataFrame(results[i])
    # decimal을 float형으로 형 변환.
    results[i] = results[i].apply(pd.to_numeric, downcast='float')
    result_list.append(list(np.array(results[i]['comments_similarity'].tolist())))

In [ ]:
draw_boxplot_for_hub(result_list, "Indegree hub & non-hub's comments similarity", xlabel, 'comments similarity')

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(8):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select m.average_is_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree = 0.1;')
sqls.append('select m.average_es_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree = 0.1;')
sqls.append('select m.average_is_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 0.1;')
sqls.append('select m.average_es_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 0.1;')
sqls.append('select m.average_is_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree <= 1;')
sqls.append('select m.average_es_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree <= 1;')
sqls.append('select m.average_is_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 1;')
sqls.append('select m.average_es_score from nodes n, mentor m where n.node_id = m.author and n.top_k_outdegree > 1;')

for i in range(8):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(8):
    results[i] = pd.DataFrame(results[i])
    # decimal을 float형으로 형 변환.
    results[i] = results[i].apply(pd.to_numeric, downcast='float')
    
    if i % 2 == 0:
        # is score.
        result_list.append(list(np.array(results[i]['average_is_score'].tolist())))
    else:
        # es score.
        result_list.append(list(np.array(results[i]['average_es_score'].tolist())))

In [ ]:
xlabel = ["0.1% hub's IS", "0.1% hub's ES", "99.9% non-hub's IS", "99.9% non-hub's ES", "1% hub's IS", "1% hub's ES", "99% non-hub's IS", "99% non-hub's ES"]
draw_boxplot_for_hub(result_list, "0.1%, 1% Outdegree hub & non-hub's average is, es score (2)", xlabel, 'average score', [1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# pymysql을 이용한 db connection.
connection = cn.make_connection('connection.csv')

cursors = []
sqls = []
results = []
result_list = []
for i in range(8):
    cursors.append(connection.cursor(pymysql.cursors.DictCursor))

sqls.append('select m.average_is_score from nodes n, mentor m where n.node_id = m.author and n.top_k_indegree = 0.1;')
sqls.append('select m.average_es_score from nodes n, mentor m where n.node_id = m.author and n.top_k_indegree = 0.1;')
sqls.append('select m.average_is_score from nodes n, mentor m where n.node_id = m.author and n.top_k_indegree > 0.1;')
sqls.append('select m.average_es_score from nodes n, mentor m where n.node_id = m.author and n.top_k_indegree > 0.1;')
sqls.append('select m.average_is_score from nodes n, mentor m where n.node_id = m.author and n.top_k_indegree <= 1;')
sqls.append('select m.average_es_score from nodes n, mentor m where n.node_id = m.author and n.top_k_indegree <= 1;')
sqls.append('select m.average_is_score from nodes n, mentor m where n.node_id = m.author and n.top_k_indegree > 1;')
sqls.append('select m.average_es_score from nodes n, mentor m where n.node_id = m.author and n.top_k_indegree > 1;')

for i in range(8):
    cursors[i].execute(sqls[i])
    # result가 dict 형태로 return.
    results.append(cursors[i].fetchall())

connection.close()

for i in range(8):
    results[i] = pd.DataFrame(results[i])
    # decimal을 float형으로 형 변환.
    results[i] = results[i].apply(pd.to_numeric, downcast='float')
    
    if i % 2 == 0:
        # is score.
        result_list.append(list(np.array(results[i]['average_is_score'].tolist())))
    else:
        # es score.
        result_list.append(list(np.array(results[i]['average_es_score'].tolist())))

In [ ]:
xlabel = ["0.1% hub's IS", "0.1% hub's ES", "99.9% non-hub's IS", "99.9% non-hub's ES", "1% hub's IS", "1% hub's ES", "99% non-hub's IS", "99% non-hub's ES"]
draw_boxplot_for_hub(result_list, "0.1%, 1% Indegree hub & non-hub's average is, es score (2)", xlabel, 'average score', [1, 2, 3, 4, 5, 6, 7, 8])

# Subreddit Analysis

In [ ]:
def combination(n, r):
    f = math.factorial
    return f(n) // f(r) // f(n-r)

In [ ]:
# Wrong Method!!
def subreddit_per_community_main_wrong(index):
    if index % 2000 == 0:
        start_index = index - 2000
    else:
        start_index = index - (index % 2000)
    
    result_for_csv = []
    
    for i in range(start_index, index):
        sql = f"select subreddit_key, cast(sum(cnt) as signed) sum from (select subreddit_key, count(subreddit_key) as cnt from comments c inner join nodes n on c.author = n.node_id where n.community_id_fastgreedy_is = {communities[i]} and c.link_key = c.parent_key and c.is_valid = 1 group by subreddit_key union all select subreddit_key, count(subreddit_key) cnt from posts p inner join nodes n on p.author = n.node_id where n.community_id_fastgreedy_is = {communities[i]} and p.is_valid=1 group by subreddit_key) a group by subreddit_key;"
        subreddit_df = cn.select_query_result_to_df(sql)
        subreddit = list(np.array(subreddit_df['subreddit_key'].tolist()))
        subreddit_count = list(np.array(subreddit_df['sum'].tolist()))

        # The number of subreddit by community
        subreddits = len(subreddit)

        # The number of comments and posts by subreddit by community
        # 하나의 subreddit에만 comments, posts가 작성되었으면 entropy는 0으로 set.
        if subreddits == 1:
            subreddit_entropy = 0
        else:
            subreddit_entropy = entropy(subreddit_count, base=subreddits)

        # idk value name...
        combination_sum = 0
        for count in subreddit_count:
            if count > 1:
                combination_sum += combination(count, 2)
        value = combination_sum / combination(sum(subreddit_count), 2)
        
        result_for_csv.append([communities[i], subreddits, subreddit_entropy, value])
        
    fields = ['community_id', 'subreddits', 'subreddit_entropy', 'value']
    cn.write_csv_for_db_update(f"/home/mykim/source/plotting-and-graph-analysis/subreddit/subreddit_analysis_{index}.csv", fields, result_for_csv)

# Best Comment

In [ ]:
def best_comment_main(index):
    sql = f'select post_key from about_posts;'
    result_df = cn.select_query_result_to_df(sql)
    post_keys = np.array(result_df['post_key'].astype(str).values.tolist())
    
    result_for_csv = []
    
    if index % 100000 == 0:
        start_index = index - 100000
    else:
        start_index = index - (index % 100000)
        
    for i in range(start_index, index):
        sql = f"select link_key, comment_key, author, score, is_score, es_score from comments where score= (select max(score) from comments where link_key='{post_keys[i]}' and link_key=parent_key and is_valid=1 and is_valid_author=1) and link_key='{post_keys[i]}' and link_key=parent_key and is_valid=1 and is_valid_author=1;"
        result_df = cn.select_query_result_to_df(sql)
        
        best_comment_cnt = len(result_df)
        
        for i in range(best_comment_cnt):
            result = result_df.iloc[i]
            result_for_csv.append([result['link_key'], result['comment_key'], result['author'], result['score'], result['is_score'], result['es_score']])
            
    fields = ['post_key', 'comment_key', 'comment_author', 'comment_score', 'is_score', 'es_score']
    cn.write_csv_for_db_update(f"post_best_comment_{index}.csv", fields, result_for_csv)

In [ ]:
index_list = [100000, 200000, 300000, 400000, 500000, 600000, 700000, 712509]

if __name__ == '__main__':
    # multi processing.
    parmap.map(best_comment_main, index_list, pm_pbar=True, pm_processes=8)